version: '3.3'
volumes:
  postgres.data:
  pg-admin4.data:

services:
#  frontend:
#    image: ktu/frontend:latest
#    container_name: ktu-frontend
#    depends_on:
#      - ktu-microservice-api
#    restart: always
#    environment:
#      - FOO=BAR
  ktu-microservice-api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: ktu-microservice-api
    depends_on:
      - psql
    ports:
      - 8383:8080 # Users  API
    restart: always
    environment:
      - NAME="KTU Students"
      - PORT=8383
  psql:
    image: postgres:11
    container_name: ktu-api-postgres
    restart: always
    volumes:
      - "postgres.data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=ktuuser
      - POSTGRES_PASSWORD=ktupass
      - POSTGRES_DB=ktu_test
      - PGDATA=/var/lib/postgresql/data/pgdata
